version: '3.8'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_nest
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: nestdb
      MYSQL_USER: root
      MYSQL_PASSWORD: root
      MYSQL_AUTHENTICATION_PLUGIN: mysql_native_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: nest_app
    restart: always
    depends_on:
      - mysql
    environment:
      DATABASE_URL: "mysql://root:root@mysql:3306/nestdb"
    ports:
      - "3000:3000"

volumes:
  mysql_data:
